### ISSUE TITLE
todo: feats

### ISSUE THREAD

**Issue by rchtgpt** [techsyndicate/tablot#12]
- [x] ask the owner to submit the empty gsheet link using the command `$ts link "<gsheet_link>" variable_name` (even the restricted link will work provided the owner has shared the gsheet with techsyndicate@tablot-280818.iam.gserviceaccount.com)

- [x] `$ts show variable_name` (by any member)

- [ ] take the format from the owner using command `$ts intro format variable_name` (like what laxya did in tsbot)

- [x] as soon as someone enters the server, tablot will PM them saying "Hey buddy! Please introduce yourself in ServerName's #introduction in the format ```blah```

- [x] after the person introduces, the sheet will automatically update with his/her info

- [x] if the same user (id) introduces again, the data will be modified

- [ ] the user will only be able to view other channels of the server after he/she has introduced themself in the correct format.

- [x] anyone can use the variable name to print the sheet inside the server

- [ ] ~~convert gsheet to excel and use certigen~~

**Comment by rchtgpt** [comment]
first and second fixed in 521f97bed05df4eb8faff0cc873de753b4d2d392
